### ISSUE TITLE
Where can I change settings like browser in VSC

### ISSUE THREAD

**Issue by xFuture603** [ritwickdey/vscode-live-server#141]
I'm submitting a question

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:

Hey guys. Its not really an issue but where can I change settings like `liveServer.settings.CustomBrowser` in Visual Studio Code? I just found the Contributions with all the settings in the Extension Overview. So where can I change this? Thank you in advance!

**Comment by xFuture603** [comment]
Sorry for my late answer! Everything is fine now! I wasnt informed about this settings file in VSC. Thank you!

**Comment by TriantafyllosFamprikatzis** [comment]
I have the same issue using VSC with Win10, but for me was because I was using Dart Sass to watch for changes and compile, so the live server is faster after I press the save button and does not see any changes.
A solution could be to delay a few seconds the live server for any other compilers to catch up.
As for any other files such as JS it works instantly with no problems,
