### ISSUE TITLE
The extension does not load on vscode

### ISSUE THREAD

**Issue by Kntalaris** [ritwickdey/vscode-live-server#2329]
- Live Server: v5.7.2
- Platform:  Windows
- Visual Studio Code: v1.63.2

**Comment by dezertdezine** [comment]
Same set-up and issue for me for last few days.

The work-around I'm using is:
Ctrl + Shift + P
Live Server: Open with Live Server (or Alt + L, Alt + O)

This opens and runs Live Server and the "Go Live" button now appears in the status bar, but still shows "Go Live" instead of the previous behaviour which was to show "Port: 5500" when running. Apart from that all works as before.

**Comment by ritwickdey** [comment]
This issue has been fixed. Let me know if you're still facing the same issue @dezertdezine

**Comment by dezertdezine** [comment]
@ritwickdey - Partially fixed (thanks). The button now works again, but the extension still doesn't load on starting Vscode I'm having to do that manually (Alt + L, Alt + O).

**Comment by ritwickdey** [comment]
Yaa. There was a performance issue. I can't enable the extension onStart. 

but if you open any HTML/JS/SVG file. The "Go Live" button should come. 

 (Or just right-click to HTML file and click to Open with live server)

**Comment by dezertdezine** [comment]
Ah OK. I'm working with PHP files, so that explains it. No problem starting it manually. Thanks for the info.

**Comment by ritwickdey** [comment]
Hi @dezertdezine  Just now I've published a new version (v5.7.4) that will fix the PHP issue. GoLive will be visible if any PHP file is opened

**Comment by dezertdezine** [comment]
Hi @ritwickdey. That works perfect now, many thanks for adding PHP and for all the work you've done on this great extension, it so good to see it being updated again.
