### ISSUE TITLE
Not working on each folder of the workspace

### ISSUE THREAD

**Issue by JFDevelopments** [ritwickdey/vscode-live-server#60]
I'm having an issue on workspace when i tried to open an index.html from specific folder inside the workspace.

**Comment by ritwickdey** [comment]
Sorry!! Can you give me an example? Where you're getting issue?

**Comment by ritwickdey** [comment]
Note: Multiroot workspace isn't supported (as of now)

**Comment by joyfementira** [comment]
Sure, For example i have a workspace and it has 5 folder with each index.html. The issue is, it is only the first folder with index.html that open on live.

**Comment by ritwickdey** [comment]
Multi root workspace is not supported yet #48

**Comment by dylanh724** [comment]
This should really be clarified in the store page since the average person has been utilizing multi root workspaces since it's release. It's just too useful. You guys do awesome work, but I sorta feel like I wasted my time and surely others have, too, until it's either implemented or disclaimed on the install page~
