### ISSUE TITLE
Opening into Chrome Canary

### ISSUE THREAD

**Issue by Stonerea656** [ritwickdey/vscode-live-server#62]
Hi, I,m wanting to open Live Server into Chrome Canary. Is this possible? Any tips? cheers

**Comment by ritwickdey** [comment]
use `liveServer.settings.AdvanceCustomBrowserCmdLine` setting... You can specify full path of any browser.

Example: 
`liveServer.settings.AdvanceCustomBrowserCmdLine : "C:\Program Files\Firefox Developer Edition\firefox.exe --private-window"`

Checkout the setting section: https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by mxschmitt** [comment]
@Stonerea656  I'm closing this for now. If you have any questions feel free to tag me and i will reopen it.

**Comment by ritwickdey** [comment]
Hi @maximelebreton, yes! because the settings file is `.json` file. 

* *JSON strings cannot be quoted with single quotes.*
*  *\\\\ is Backslash character for JSON*

**Comment by maximelebreton** [comment]
Thanks @ritwickdey, so can you specify it in your https://github.com/ritwickdey/vscode-live-server/issues/62#issuecomment-356560272 example, because it is confusing. 
same confusion for the `liveServer.settings.AdvanceCustomBrowserCmdLine` example on https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

It's not a big deal, but it avoids wasting time understanding why the example doesn't work :)

**Comment by gambhirsharma** [comment]
For Mac users: 

```
"liveServer.settings.AdvanceCustomBrowserCmdLine": "/Applications/Google Chrome Canary.app"
```
