### ISSUE TITLE
Paused on exception DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by ozknozsrt** [ritwickdey/vscode-live-server#67]
Hi,

Im using vsCode.  This problem came after you changed the codes. Automatically switched to debugger mode.
http://prntscr.com/i22514

Why could it be?

**Comment by ritwickdey** [comment]
Sorry? I don't understand. 

I guess, you don't have `<head>` tag or `<link>` element not inside `<head>` tag?

**Comment by ozknozsrt** [comment]
No, smoothly.

http://prntscr.com/i23gw6

**Comment by ritwickdey** [comment]
Ok! I don't know why exactly the issue is happening in your machine. 

But this issue is related #41 (Due to CSS inject)

**Comment by ritwickdey** [comment]
I made a option, so that you make disable the CSS inject. https://github.com/ritwickdey/vscode-live-server/commit/ab14885592feb856f7cf752dc7c1eb994a6374df

Soon, It will be live on VSCODE MARKETPLACE.
After updating to v3.1.0 you'll get a setting  `liveServer.settings.fullReload`. Set its value `true` to prevent CSS inject.
